// Generated by CoffeeScript 1.4.0
(function() {

  define("Config", function() {
    var Config;
    Config = {
      baseURL: "http://localhost:3000"
    };
    window.conf = Config;
    return Config;
  });

}).call(this);
