// Generated by CoffeeScript 1.7.1
(function() {
  var app, router;

  app = {};

  app.Router = Backbone.Router.extend({
    routes: {
      "*default": "default"
    },
    "default": function() {
      return alert('nothing else matters...');
    }
  });

  router = new app.Router();

  Backbone.history.start();

}).call(this);
