// Generated by CoffeeScript 1.4.0
(function() {

  define("Views/CreditCard", ["Models/CreditCard", "Collections/CreditCard"], function(CreditCard, CreditCardCollection) {
    var CreditCardView;
    return CreditCardView = Backbone.View.extend({
      el: $(".pr-creditcard"),
      events: {
        "change .pr-creditcard-select": "updateToSelected",
        "keyup": "updateModel"
      },
      updateToSelected: function() {
        var newModel;
        newModel = this.collection.get($(".pr-creditcard select :selected").val());
        this.model = newModel || this.model;
        this.updateParent();
        return this.render();
      },
      updateParent: function() {
        this.parentModel.set("credit_card", this.model);
        return this.parentModel.trigger("change");
      },
      updateModel: function() {
        this.model.set({
          card_holder: this.$el.find('.pr-creditcard-form-cardholder').val(),
          expiration_month: this.$el.find('.pr-creditcard-form-expire').val(),
          expiration_year: this.$el.find('.pr-creditcard-form-expire-year').val(),
          number: this.$el.find('.pr-creditcard-form-number').val()
        });
        return this.updateParent();
      },
      initialize: function(options) {
        var _this = this;
        if (options == null) {
          options = {};
        }
        this.model = new CreditCard;
        this.parentModel = options.parentModel;
        this.collection = new CreditCardCollection;
        this.collection.fetch({
          success: function() {
            _this.model = _this.collection.first();
            return _this.updateToSelected();
          }
        });
        this.updateParent();
      },
      template: Handlebars.compile($("#pr-creditcard").html()),
      templateForm: Handlebars.compile($("#pr-creditcard-form").html()),
      render: function() {
        var selected;
        selected = $(".pr-creditcard select :selected").val();
        this.$el.html(this.template({
          cards: this.collection.toJSON()
        }));
        if (selected === "new") {
          this.$el.append(this.templateForm());
        }
        $(".pr-creditcard select [value=" + selected + "]").attr("selected", "selected");
      }
    });
  });

}).call(this);
