// Generated by CoffeeScript 1.4.0
(function() {

  define("Views/Enchanced", function() {
    var EnchancedView;
    return EnchancedView = Backbone.View.extend({
      updateToSelected: function(event) {
        var newModel, selected;
        selected = event.target.value;
        if (selected === "new") {
          this.updateModel();
        } else {
          if ((newModel = this.collection.get(selected))) {
            this.model.set(newModel.toJSON());
          }
        }
        return this.render(selected);
      },
      updateModel: function() {
        var attr, newAttrs, selector, _ref;
        newAttrs = {};
        _ref = this.form;
        for (attr in _ref) {
          selector = _ref[attr];
          newAttrs[attr] = this.$el.find(selector).val();
        }
        this.model.set(newAttrs);
        return this.model.unset("id");
      }
    });
  });

}).call(this);
