// Generated by CoffeeScript 1.4.0
(function() {

  define("Views/Error", ["Models/PurchaseRequest"], function(PurchaseRequest) {
    var Error;
    return Error = Backbone.View.extend({
      el: $('.pr-error'),
      template: Handlebars.compile($("#pr-error").html()),
      render: function(error) {
        return this.$el.html(this.template({
          error: error
        }));
      },
      unrender: function() {
        return this.$el.html("");
      }
    });
  });

}).call(this);
