// Generated by CoffeeScript 1.4.0
(function() {

  define("Views/Error", function() {
    var Error;
    return Error = Backbone.View.extend({
      template: Handlebars.compile($("#pr-error").html()),
      initialize: function(options) {
        this.listenTo(this.model, "invalid", this.renderValidation);
        this.listenTo(this.model, "error", this.renderServer);
        return this.listenTo(this.model, "request", this.unrender);
      },
      renderValidation: function(model, validationError) {
        var _this = this;
        return _.defer(function() {
          return _this.$el.html(_this.template({
            error: validationError
          }));
        });
      },
      renderServer: function(model, xhr) {
        var _this = this;
        return _.defer(function() {
          return _this.$el.html(_this.template({
            error: xhr.responseJSON.error
          }));
        });
      },
      unrender: function() {
        var _this = this;
        return _.defer(function() {
          return _this.$el.html("");
        });
      }
    });
  });

}).call(this);
