// Generated by CoffeeScript 1.4.0
(function() {

  define("Views/Form", ["Models/PurchaseRequest", "Models/Address", "Models/CreditCard", "Views/Address", "Views/CreditCard"], function(PurchaseRequest, Address, CreditCard, AddressView, CreditCardView) {
    var Form;
    return Form = Backbone.View.extend({
      initialize: function() {
        this.creditCardView = new CreditCardView({
          parentModel: this.model
        });
        this.shippingView = new AddressView({
          el: $('.pr-address-shipping'),
          parentModel: this.model
        });
        return this.billingView = new AddressView({
          el: $('.pr-address-billing'),
          parentModel: this.model,
          samePossible: true
        });
      }
    });
  });

}).call(this);
