// Generated by CoffeeScript 1.7.1
(function() {
  define("Views/Form", ["Models/PurchaseRequest", "Models/Address", "Models/CreditCard", "Views/Address", "Views/CreditCard"], function(PurchaseRequest, Address, CreditCard, AddressView, CreditCardView) {
    var Form;
    return Form = Backbone.View.extend({
      initialize: function() {
        this.creditCardView = new CreditCardView({
          model: this.model.creditCard
        });
        this.shippingView = new AddressView({
          el: $('.pr-address-shipping'),
          model: this.model.shippingAddress
        });
        return this.billingView = new AddressView({
          el: $('.pr-address-billing'),
          model: this.model.billingAddress,
          samePossible: true
        });
      },
      template: Handlebars.compile($(".pr-form").html()),
      render: function() {}
    });
  });

}).call(this);
