// Generated by CoffeeScript 1.4.0
(function() {

  define("Views/Global", ['Views/Form', 'Views/Summary', 'Views/Error', 'Models/PurchaseRequest'], function(FormView, SummaryView, ErrorView, PurchaseRequest) {
    var GlobalView;
    return GlobalView = Backbone.View.extend({
      events: {
        "click .pr-send": "send"
      },
      initialize: function() {
        this.model = new PurchaseRequest;
        this.formView = new FormView({
          model: this.model
        });
        this.summaryView = new SummaryView({
          model: this.model
        });
        this.errorView = new ErrorView({
          model: this.model
        });
        this.listenTo(this.model, "invalid", this.error);
      },
      send: function() {
        var _ref;
        if ((_ref = this.errorView) != null) {
          _ref.unrender();
        }
        console.log(this.model.toJSON());
        return this.model.save({}, {
          success: this.redirect,
          error: this.error
        });
      },
      error: function(model, response) {
        var error, _ref;
        console.log("houston, we've got problem");
        console.log(response);
        console.log(model);
        if (model.validationError != null) {
          error = response;
        }
        if (((_ref = response.responseJSON) != null ? _ref.error : void 0) != null) {
          error = response.responseJSON.error;
        }
        if ((response.status != null) && response.status === 500) {
          $('.pr-send').attr('disabled', 'disabled');
        }
        this.errorView = new ErrorView({
          model: this.model
        });
        this.errorView.render(error);
      },
      redirect: function(response) {},
      render: function() {
        this.formView.render();
        this.summaryView.render();
      }
    });
  });

}).call(this);
