// Generated by CoffeeScript 1.7.1
(function() {
  define("Views/Global", ['Views/Form', 'Views/Summary', 'Models/PurchaseRequest'], function(FormView, SummaryView, PurchaseRequest) {
    var GlobalView;
    return GlobalView = Backbone.View.extend({
      events: {
        "click .pr-send": "send",
        "change model": "logChange"
      },
      logChange: function() {
        return console.log("change event was fired");
      },
      initialize: function() {
        this.model = new PurchaseRequest;
        this.formView = new FormView({
          model: this.model
        });
        this.summaryView = new SummaryView({
          model: this.model
        });
      },
      send: function() {
        console.log(this.model);
        return Backbone.sync("create", this.model, {
          success: this.redirect,
          error: this.error
        });
      },
      error: function(response) {
        var res;
        console.log(response);
        res = response.responseJSON;
        console.log({
          message: res.error,
          code: response.status,
          code_message: response.statusText
        });
      },
      redirect: function(response) {
        if (response.success === "true") {

        } else {
          alert('fuck');
        }
      },
      render: function() {
        this.formView.render();
        this.summaryView.render();
      }
    });
  });

}).call(this);
