// Generated by CoffeeScript 1.4.0
(function() {

  define("Views/Send", function() {
    var SendView;
    return SendView = Backbone.View.extend({
      events: {
        "click": "send"
      },
      initialize: function(options) {
        return this.listenTo(this.model, "error", this.handleError);
      },
      send: function() {
        return this.model.save({
          success: function(model, xhr) {
            return window.location.replace(xhr.redirect_url.toString());
          }
        });
      },
      handleError: function(model, xhr) {
        if (xhr.status === 500) {
          return this.$el.attr('disabled', 'disabled');
        }
      }
    });
  });

}).call(this);
