// Generated by CoffeeScript 1.4.0
(function() {

  define("Views/Summary", ["Models/PurchaseRequest"], function(PurchaseRequest) {
    var SummaryView;
    return SummaryView = Backbone.View.extend({
      el: $('.pr-summary'),
      initialize: function() {
        return this.listenTo(this.model, "change", this.render);
      },
      template: Handlebars.compile($("#pr-summary").html()),
      render: function() {
        console.log("rendering summary");
        return this.$el.html(this.template(JSON.stringify(this.model)));
      }
    });
  });

}).call(this);
