// Generated by CoffeeScript 1.4.0
(function() {

  define("Views/Summary", ["Models/PurchaseRequest"], function(PurchaseRequest) {
    var SummaryView;
    return SummaryView = Backbone.View.extend({
      el: $('.pr-summary'),
      events: {
        "change model": "render"
      },
      initialize: function() {
        return this.listenTo(this.model, "change", this.render);
      },
      template: Handlebars.compile($("#pr-summary").html()),
      render: function() {
        return this.$el.html(this.template(this.model.toJSON()));
      }
    });
  });

}).call(this);
