// Generated by CoffeeScript 1.4.0
(function() {

  define('Tests/spec/', [], function() {
    return describe('', function() {
      beforeEach(function() {
        return this.el = $('.test');
      });
      afterEach(function() {
        return this.el.empty();
      });
      return it('', function() {});
    });
  });

}).call(this);
