// Generated by CoffeeScript 1.4.0
(function() {

  define('Tests/spec/modelNested', ['Models/Nested'], function(NestedModel) {
    'use strict';
    return describe("Models :: Nested", function() {
      return it("should raise event on parent model", function() {
        var model, parentModel, spy;
        parentModel = {};
        _.extend(parentModel, Backbone.Events);
        spy = jasmine.createSpy();
        parentModel.listenTo(parentModel, "change", spy);
        model = new NestedModel({
          parent: parentModel
        });
        model.set({
          "test": "data"
        });
        return expect(spy).toHaveBeenCalled();
      });
    });
  });

}).call(this);
