// Generated by CoffeeScript 1.4.0
(function() {

  define('Tests/spec/modelCountry', ['Models/Country'], function(Country) {
    return describe('Models :: Country', function() {
      beforeEach(function() {
        var _this = this;
        localStorage.clear();
        this.model = new Country;
        this.res = [];
        this.res.push({
          code: "lol",
          name: "lolregion"
        });
        this.res.push({
          code: "some",
          name: "someregion"
        });
        return this.model.regions.sync = function(action, obj, options) {
          return options.success(_this.res);
        };
      });
      it('should return lists of regions', function() {
        this.model.regions.fetch();
        return expect(this.model.regions.toJSON()).toEqual(this.res);
      });
      return it('should access server only once (use cache)', function() {
        spyOn(this.model.regions, 'sync').and.callThrough();
        this.model.regions.fetch();
        this.model.regions.fetch();
        return expect(this.model.regions.sync.calls.count()).toEqual(1);
      });
    });
  });

}).call(this);
