// Generated by CoffeeScript 1.4.0
(function() {

  define('Tests/spec/viewAddress', ['Views/Address'], function(AddressView) {
    return describe('Views :: Enchanced :: Address', function() {
      beforeEach(function() {
        var i, prop, tmp, _i, _j, _len, _model, _ref;
        this.el = $('.test');
        _model = Backbone.Model.extend({
          defaults: {
            'address': new Backbone.Model
          }
        });
        this.res = [];
        for (i = _i = 1; _i <= 10; i = _i += 1) {
          tmp = {};
          _ref = ['address', 'address2', 'country', 'region', 'locality'];
          for (_j = 0, _len = _ref.length; _j < _len; _j++) {
            prop = _ref[_j];
            tmp[prop] = "" + i + " " + prop;
          }
          this.res.push(tmp);
        }
        this.collection = new (Backbone.Collection.extend({
          model: _model
        }));
        window.app = {
          collections: {
            addresses: this.collection
          }
        };
        this.parentModel = new _model;
        this.view = new AddressView({
          el: this.el,
          parentModel: this.parentModel
        });
        return this.collection.reset(this.res);
      });
      afterEach(function() {
        return this.el.empty();
      });
      return it('should initialize model with first model from collection', function() {
        this.collection.trigger("sync");
        return expect(this.parentModel.get('address').toJSON()).toEqual(this.collection.first().toJSON());
      });
    });
  });

}).call(this);
