// Generated by CoffeeScript 1.4.0
(function() {

  define('Tests/spec/viewSend', ["Views/Send"], function(SendView) {
    return describe('Views :: Send', function() {
      beforeEach(function() {
        this.el = $('.test');
        this.model = new Backbone.Model;
        return this.view = new SendView({
          model: this.model,
          el: this.el
        });
      });
      afterEach(function() {
        return this.el.empty();
      });
      return it('should disable el, if error’s status is 500', function() {
        this.model.trigger('error', this.model, {
          status: 500
        });
        return expect(this.el.attr('disabled')).toEqual('disabled');
      });
    });
  });

}).call(this);
