// Generated by CoffeeScript 1.4.0
(function() {

  define('Tests/spec/viewEnchanced', ['Views/Enchanced'], function(EnchancedView) {
    return describe('Views :: Enchanced', function() {
      beforeEach(function() {
        var tmp_model, tmp_model2, _collection, _model;
        this.el = $('.test');
        _model = Backbone.Model.extend({
          defaults: {
            'first': '',
            'second': ''
          }
        });
        _collection = Backbone.Collection.extend({
          model: _model
        });
        tmp_model = new _model;
        tmp_model.set({
          first: 'true',
          second: 'false',
          id: 1
        });
        tmp_model2 = new _model;
        tmp_model2.set({
          first: 'nope',
          second: 'yep',
          id: 123
        });
        this.collection = new _collection;
        this.collection.reset([tmp_model, tmp_model2]);
        this.model = new _model;
        return this.view = new EnchancedView({
          collection: this.collection,
          model: this.model,
          el: this.el
        });
      });
      afterEach(function() {
        return this.el.empty();
      });
      it('should update model to selected from list', function() {
        this.el.append('<select><option value="123">some</option></select>');
        this.view.updateToSelected({
          target: {
            value: '123'
          }
        });
        return expect(this.model.get('first')).toEqual('nope');
      });
      return it('should update model to inputs\' values', function() {
        this.el.append('<input class="test1" value="lol"><input class="test2" value="lol2">');
        this.view.form = {
          'first': '.test1',
          'second': '.test2'
        };
        this.view.updateModel();
        expect(this.model.get('first')).toEqual('lol');
        return expect(this.model.get('second')).toEqual('lol2');
      });
    });
  });

}).call(this);
