// Generated by CoffeeScript 1.4.0
(function() {

  define('Tests/spec/viewCreditCard', ['Views/CreditCard'], function(CreditCardView) {
    return describe('Views :: Enchanced :: CreditCard', function() {
      beforeEach(function() {
        var i, prop, tmp, _i, _j, _len, _parentModel, _ref;
        this.el = $('.test');
        _parentModel = Backbone.Model.extend({
          defaults: {
            'credit_card': new Backbone.Model
          }
        });
        this.parentModel = new _parentModel;
        this.res = [];
        for (i = _i = 1; _i <= 10; i = _i += 1) {
          tmp = {};
          _ref = ['number', 'cardholder', 'expiration_month', 'expiration_year'];
          for (_j = 0, _len = _ref.length; _j < _len; _j++) {
            prop = _ref[_j];
            tmp[prop] = "" + i + " " + prop;
          }
          this.res.push(tmp);
        }
        this.collection = new (Backbone.Collection.extend({
          model: _parentModel
        }));
        window.app = {
          collections: {
            cards: this.collection
          }
        };
        this.view = new CreditCardView({
          el: this.el,
          parentModel: this.parentModel
        });
        return this.collection.reset(this.res);
      });
      afterEach(function() {
        return this.el.empty();
      });
      return it('should initialize model with first model from collection', function() {
        this.collection.trigger("sync");
        return expect(this.parentModel.get('credit_card').toJSON()).toEqual(this.collection.first().toJSON());
      });
    });
  });

}).call(this);
