// Generated by CoffeeScript 1.7.1
(function() {
  define("Models/Country", function() {
    var Country, Region, RegionCollection;
    Region = Backbone.Model.extend({
      attributes: {
        code: "",
        name: ""
      }
    });
    RegionCollection = Backbone.Collection.extend({
      model: Region,
      url: function() {
        return "http://jsonstub.com" + "/countries/" + this.attributes.code + "/regions";
      }
    });
    Country = Backbone.Model.extend({
      attributes: {
        code: "",
        country: ""
      },
      regions: RegionCollection
    });
    return Country;
  });

}).call(this);
