// Generated by CoffeeScript 1.4.0
(function() {

  define("Models/CreditCard", function() {
    var CreditCard;
    return CreditCard = Backbone.Model.extend({
      attributes: {
        number: "",
        cardholder: "",
        expires: ""
      },
      defaults: {
        number: "1234123412341234",
        cardholder: "Ivan Ivanov",
        expires: "2034/12"
      }
    });
  });

}).call(this);
