// Generated by CoffeeScript 1.4.0
(function() {

  define("Models/CreditCard", function() {
    var CreditCard;
    CreditCard = Backbone.Model.extend({
      attributes: {
        number: "",
        cardholder: "",
        expiration_month: "",
        expiration_year: ""
      },
      validate: function(attributes) {
        var expire_date, number, today_date;
        if (attributes == null) {
          attributes = this.attributes;
        }
        if (_.isEmpty(attributes)) {
          return "Credit card fields are not filled";
        }
        if (_.isEmpty(attributes.expiration_month || _.isEmpty(attributes.expiration_year))) {
          return "Credit card: expiration date is incomplete";
        }
        if (_.isEmpty(attributes.number)) {
          return "Credit card: card number is empty";
        }
        if (_.isEmpty(attributes.card_holder)) {
          return "Credit card: cardholder is empty";
        }
        number = parseInt(this.attributes.number.split(" ").join(""), 10);
        expire_date = new Date("" + attributes.expiration_month + "/1/" + attributes.expiration_year);
        expire_date.setMonth(expire_date.getMonth + 1);
        today_date = new Date();
        if (expire_date - today_date <= 0) {
          return "Already expired credit card!";
        }
      }
    });
    return CreditCard;
  });

}).call(this);
