// Generated by CoffeeScript 1.4.0
(function() {

  define("Models/Nested", function() {
    var NestedModel;
    return NestedModel = Backbone.Model.extend({
      initialize: function(options) {
        if (options == null) {
          options = {};
        }
        return this.parent = options.parent || void 0;
      },
      set: function(attrs, options) {
        if (this.parent != null) {
          this.parent.trigger("change");
        }
        return Backbone.Model.prototype.set.call(this, attrs, options);
      },
      isEmpty: function() {
        var beautiful_name, error, name, value, _ref;
        error = "";
        _ref = this.attributes;
        for (name in _ref) {
          value = _ref[name];
          if (_.isEmpty(value) && (name !== 'id' && name !== 'address2')) {
            beautiful_name = name.replace("_", " ");
            beautiful_name = beautiful_name[0].toUpperCase() + beautiful_name.slice(1);
            error += "" + beautiful_name + " is empty. ";
          }
        }
        if (error.length > 0) {
          return error.trim();
        }
      }
    });
  });

}).call(this);
