// Generated by CoffeeScript 1.7.1
(function() {
  define("Models/PurchaseRequest", ["Models/Address", "Models/CreditCard"], function(Address, CreditCard) {
    var PurchaseRequest;
    return PurchaseRequest = Backbone.Model.extend({
      attributes: {
        creditCard: CreditCard,
        shippingAddress: Address,
        billingAddress: Address
      },
      url: function() {
        return "http://jsonstub.com" + "/orders";
      },
      toJSON: function() {
        var _ref, _ref1, _ref2;
        return {
          creditCard: (_ref = this.attributes.creditCard) != null ? _ref.toJSON() : void 0,
          shippingAddress: (_ref1 = this.attributes.shippingAddress) != null ? _ref1.toJSON() : void 0,
          billingAddress: (_ref2 = this.attributes.billingAddress) != null ? _ref2.toJSON() : void 0
        };
      }
    });
  });

}).call(this);
