// Generated by CoffeeScript 1.7.1
(function() {
  describe("my awesome purchase requset app", function() {
    return describe("validation", function() {
      return it("should discard expired credit card data", function() {
        var credit_card;
        return credit_card = new App.CreditCard({
          expired_month: 5,
          expired_year: 2013,
          card_holder: "Петрович"
        });
      });
    });
  });

}).call(this);
