// Generated by CoffeeScript 1.4.0
(function() {

  describe("my awesome purchase requset app", function() {
    return describe("validation", function() {
      it("should discard expired credit card data", function() {
        var credit_card;
        credit_card = new App.CreditCard({
          expired_month: 2,
          expired_year: 2013,
          card_holder: "Chelyabinsk Metheorite"
        });
        return expect(credit_card.validate().toBeFalsy());
      });
      it("should discard credit card with month > 12", function() {
        var credit_card;
        credit_card = new App.CreditCard({
          expired_month: 13,
          expired_year: 2014,
          card_holder: "Premium User"
        });
        return expect(credit_card.validate().toBeFalsy());
      });
      it("should accept credit card which doesn't expire", function() {
        var credit_card;
        credit_card = new App.CreditCard({
          expired_month: Date().getMonth(),
          expired_year: Date().getFullYear(),
          card_holder: "Evergreen"
        });
        return expect(credit_card.validate().toBeTruthy());
      });
      return it("should discard address if region does not belong to country", function() {
        var address;
        address = new App.Address({
          address: "Sadovaya 25, 3",
          country: "USA",
          region: "SPB",
          locality: "Saint-Petersburg"
        });
        return expect(address.validate().toBeFalsy());
      });
    });
  });

}).call(this);
