// Generated by CoffeeScript 1.4.0
(function() {

  define("Collections/Address", ["Models/Address", "Models/Country", "Collections/Country", "Config"], function(Address, Country, CountryCollection, Config) {
    var AddressCollection;
    return AddressCollection = Backbone.Collection.extend({
      url: function() {
        return Config.baseURL + "/addresses";
      },
      model: Address
    });
  });

}).call(this);
