// Generated by CoffeeScript 1.4.0
(function() {

  define("Collections/Country", ["Models/Country", "Config"], function(Country, Config) {
    var CountryCollection;
    return CountryCollection = Backbone.Collection.extend({
      model: Country,
      url: function() {
        return Config.baseURL + "/countries";
      }
    });
  });

}).call(this);
