// Generated by CoffeeScript 1.4.0
(function() {

  define("Collections/Country", ["Models/Country"], function(Country) {
    var CountryCollection;
    return CountryCollection = Backbone.Collection.extend({
      model: Country,
      url: "http://localhost:3000" + "/countries"
    });
  });

}).call(this);
