// Generated by CoffeeScript 1.7.1
(function() {
  define("Collections/Country", ["Models/Country"], function(Country) {
    var CountryCollection, _regionCache;
    return CountryCollection = Backbone.Collection.extend({
      model: Country,
      url: "http://jsonstub.com" + "/countries"
    }, _regionCache = {
      "US": [
        {
          code: "LOL",
          name: "Yepaons"
        }
      ]
    }, {
      _loadRegions: function(code) {
        return _regionCache[code] = [
          {
            code: "cache yep",
            name: "suoeefe"
          }
        ];
      },
      getRegions: function(code) {
        if (cache[code] != null) {
          return cache[code];
        } else {
          _loadRegions(code);
          return cache[code];
        }
      }
    });
  });

}).call(this);
