// Generated by CoffeeScript 1.4.0
(function() {

  define("Collections/CreditCard", ["Models/CreditCard"], function(CreditCard) {
    var CreditCardCollection;
    return CreditCardCollection = Backbone.Collection.extend({
      url: "/credit_cards",
      model: CreditCard
    });
  });

}).call(this);
