// Generated by CoffeeScript 1.4.0
(function() {

  define("Collections/CreditCard", ["Models/CreditCard", "Config"], function(CreditCard, Config) {
    var CreditCardCollection;
    return CreditCardCollection = Backbone.Collection.extend({
      url: function() {
        return Config.baseURL + "/credit_cards";
      },
      model: CreditCard
    });
  });

}).call(this);
