// Generated by CoffeeScript 1.7.1
(function() {
  define("Collections/CreditCard", ["Models/CreditCard"], function(CreditCard) {
    var CreditCardCollection;
    return CreditCardCollection = Backbone.Collection.extend({
      url: "http://jsonstub.com" + "/credit_cards",
      model: CreditCard
    });
  });

}).call(this);
